# Generated by Django 3.2.7 on 2023-12-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('authentication', '0007_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.resume'),
        ),
    ]
