# Generated by Django 3.2.7 on 2023-12-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=225, null=True)),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('state', models.CharField(blank=True, max_length=225, null=True)),
                ('country', models.CharField(blank=True, max_length=225, null=True)),
                ('degree', models.CharField(blank=True, max_length=225, null=True)),
                ('major', models.CharField(blank=True, max_length=225, null=True)),
                ('start', models.CharField(blank=True, max_length=225, null=True)),
                ('end', models.CharField(blank=True, max_length=225, null=True)),
                ('graduated', models.BooleanField(blank=True, null=True)),
                ('electives', models.JSONField(blank=True, null=True)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=225, null=True)),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('state', models.CharField(blank=True, max_length=225, null=True)),
                ('country', models.CharField(blank=True, max_length=225, null=True)),
                ('start', models.CharField(blank=True, max_length=225, null=True)),
                ('end', models.CharField(blank=True, max_length=225, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=225, null=True)),
                ('middle', models.CharField(blank=True, max_length=225, null=True)),
                ('last', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('tools', models.JSONField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools', models.JSONField(blank=True, null=True)),
                ('concepts', models.JSONField(blank=True, null=True)),
                ('services', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educations', models.ManyToManyField(to='api.Education')),
                ('experiences', models.ManyToManyField(to='api.Experience')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('projects', models.ManyToManyField(to='api.Project')),
                ('skills', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
        ),
    ]
